name: "Build Harbor from Source Code"
env:
  REGISTRYSERVER=registry.cn-beijing.aliyuncs.com/
  REGISTRYPROJECTNAME=llaoj

on:
  push:

jobs:
  BUILD_JOBSERVICE:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         path: src/github.com/llaoj/harbor
      - name: Build with official Golang image
        run: |
          set -x
          cd src/github.com/llaoj/harbor
          pwd
          env
          make compile COMPILETAG=compile_golangimage
          make build COMPILETAG=compile_golangimage
          make pushimage -e DEVFLAG=false REGISTRYSERVER=$REGISTRYSERVER REGISTRYUSER=${{ secrets.REGISTRY_USERNAME }} REGISTRYPASSWORD=${{ secrets.REGISTRY_PASSWORD }} REGISTRYPROJECTNAME=$REGISTRYPROJECTNAME